import Head from "next/head";
import styles from "../styles/Home.module.css";
import Arweave from "arweave";
import { readContract, selectWeightedPstHolder } from "smartweave";

export default function Home() {
  const arweave = Arweave.init({});
  const pstContractId = "3bhJb6k6qyhI4nzShPQuvdsehmv63HiYAeGd5E3ipCs";

  async function sendFee() {
    const contractState = await readContract(arweave, pstContractId);
    const holder = selectWeightedPstHolder(contractState.balances);
    const tx = await arweave.createTransaction({
      target: holder,
      quantity: arweave.ar.arToWinston("0.1"),
    });
    await arweave.transactions.sign(tx)
    const response = await arweave.transactions.post(tx)
    console.log(response.status)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, Arweave!</h1>
      <button onClick={sendFee}>Send Fee!</button>
    </div>
  );
}
